version: '3.8'
services:
  service-notes-backend:
    container_name: notes-backend
    image: testing_notes_backend:latest
    build:
      context: .
      dockerfile: notes-app-be/docker/Dockerfile
      target: development
      args:
        NODE_ENV: dev
    ports:
      - 3000:3000 # HTTP port
      - 3002:3002 # WebSocket port (add this line)
    env_file:
      - ./notes-app-be/.env/be.env
    networks:
      dev_network:
        ipv4_address: 30.3.3.200
    volumes:
      - ./notes-app-be/src:/home/dev/backend/src
      - ./notes-app-be/node_modules:/home/dev/backend/node_modules/
    command: npm run start:debug

  service-notes-frontend:
    container_name: notes-frontend
    image: testing_notes_frontend:latest
    build:
      context: .
      dockerfile: notes-app-fe/docker/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - ./notes-app-fe/.env
    networks:
      dev_network:
        ipv4_address: 30.3.4.202
    volumes:
      - ./notes-app-fe:/home/dev/frontend
    command: npm run start

networks:
  dev_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 30.3.0.0/16